FROM desertbit/crossbuild:base
MAINTAINER team@desertbit.com

ENV CROSS_TRIPLE=x86_64-ubuntu16.04-linux-gnu \
    CMAKE_SYSTEM_NAME=Linux \
    CMAKE_SYSTEM_PROCESSOR=x86_64 \
    GOOS=linux \
    GOARCH=amd64

#import common.toolchain

RUN build-toolchain