FROM desertbit/crossbuild:base
MAINTAINER team@desertbit.com

ENV CROSS_TRIPLE=armv7-rpi2-linux-gnueabihf \
    CMAKE_SYSTEM_NAME=Linux \
    CMAKE_SYSTEM_PROCESSOR=arm \
    GOOS=linux \
    GOARCH=arm \
    GOARM=7

#import common.toolchain

RUN build-toolchain