FROM desertbit/crossbuild:base
MAINTAINER team@desertbit.com

ENV CROSS_TRIPLE=i686-ubuntu16.04-linux-gnu \
    CMAKE_SYSTEM_NAME=Linux \
    CMAKE_SYSTEM_PROCESSOR=x86 \
    GOOS=linux \
    GOARCH=386

#import common.toolchain

RUN build-toolchain
