FROM desertbit/crossbuild:base
MAINTAINER team@desertbit.com

ENV CROSS_TRIPLE=x86_64-w64-mingw32 \
    CMAKE_SYSTEM_NAME=Windows \
    CMAKE_SYSTEM_PROCESSOR=x86_64 \
    GOOS=windows \
    GOARCH=amd64

#import common.toolchain

RUN build-toolchain